import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fixture } from './chatgpt-fixture.mjs';
const directory = await mkdtemp(path.resolve('.test-parallel-'));
const bootstrap = path.join(directory, 'fixture.cjs');
await writeFile(bootstrap, `const {app}=require('electron'); app.on('session-created', s=>s.protocol.handle('https',()=>new Response(${JSON.stringify(fixture)}, {headers:{'Content-Type':'text/html'}}))); require(${JSON.stringify(path.resolve('dist-electron/main.cjs'))});`);
const env={...process.env,WORKSPACE_USER_DATA:directory}; delete env.ELECTRON_RUN_AS_NODE; delete env.WORKSPACE_DEV_URL;
let desktop;
try {
 desktop=await electron.launch({args:['--no-sandbox',bootstrap],env});
 const page=await desktop.firstWindow(); await page.waitForFunction(()=>!!window.workspace);
 const rpc=(method,params={})=>page.evaluate(({method,params})=>window.workspace.call(method,params),{method,params});
 const until=async (condition)=>{const deadline=Date.now()+20000; while(!await condition()){assert.ok(Date.now()<deadline,'condition timed out');await new Promise(r=>setTimeout(r,100));}};
 const account=await rpc('accounts.create',{name:'Parallel'});
 await until(async()=> (await rpc('browser.inspect',{accountId:account.id})).readiness==='ready');
 assert.equal(await page.locator('.conversation-tabs').count(),0,'Single page needs no tab strip');
 const manual=(await rpc('workspace.status')).page;
 const execute=async(url,script)=>desktop.evaluate(async({webContents,session},{url,script,partition})=>{
  const wc=webContents.getAllWebContents().find(wc=>wc.session===session.fromPartition(partition)&&wc.getURL()===url);
  if(!wc)throw new Error('Missing page '+url);return wc.executeJavaScript(script);
 },{url,script,partition:account.partition});
 await execute(manual.url,"history.pushState({},'', '/c/manual'); window.fixtureHold=true; document.querySelector('textarea').value='Original manual reply'; document.querySelector('[data-testid=send-button]').click(); localStorage.setItem('shared-login-check','same-account')");
 const original='https://chatgpt.com/c/manual';
 const a=await rpc('tasks.create',{accountId:account.id,new:true,idempotencyKey:'parallel-a',input:{type:'prompt',prompt:'HOLD:A',submit:true}});
 const follow=await rpc('tasks.create',{accountId:account.id,conversation:a.conversationId,input:{type:'prompt',prompt:'Follow A',submit:true}});
 const b=await rpc('tasks.create',{accountId:account.id,new:true,idempotencyKey:'parallel-b',input:{type:'prompt',prompt:'Independent B',submit:true}});
 await until(async()=> (await rpc('tasks.get',{id:b.id})).status==='done');
 assert.equal((await rpc('tasks.get',{id:a.id})).status,'running');
 assert.equal((await rpc('tasks.get',{id:follow.id})).status,'pending');
 assert.equal(await execute(original,"!!document.querySelector('[data-testid=stop-button]')"),true,'Original manual reply is still generating');
 assert.equal(await execute(original,'window.fixtureSendCount'),1,'Original page was neither navigated nor sent another question');
 const state=await rpc('workspace.status'); assert.equal(state.pages.length,3);
 const aPage=state.pages.find(item=>item.conversationId===a.conversationId);
 const bPage=state.pages.find(item=>item.conversationId===b.conversationId);
 assert.notEqual(aPage.id,bPage.id);assert.notEqual(aPage.url,bPage.url);
 assert.equal(await execute(bPage.url,"localStorage.getItem('shared-login-check')"),'same-account');
 await until(async()=> (await rpc('notifications.list',{accountId:account.id})).filter(n=>n.running).length===2);
 assert.equal((await rpc('notifications.list',{accountId:account.id})).filter(n=>n.unread).length,1);
 await rpc('browser.select',{accountId:account.id,pageId:aPage.id});
 await page.locator('.preview-canvas img').waitFor();
 assert.equal((await rpc('browser.preview',{accountId:account.id,pageId:manual.id})),null,'Manual page is not locked by another conversation');
 const b2=await rpc('tasks.create',{accountId:account.id,conversation:b.conversationId,input:{type:'prompt',prompt:'HOLD:B',submit:true}});
 await until(async()=>!!(await rpc('tasks.get',{id:b2.id})).submittedAt);
 await rpc('queues.takeover',{accountId:account.id,conversation:a.conversationId});
 assert.equal((await rpc('tasks.get',{id:a.id})).status,'uncertain');
 assert.equal((await rpc('tasks.get',{id:b2.id})).status,'running','Taking over A cannot interrupt B');
 const after=await rpc('workspace.status');
 assert.equal(after.pages.find(p=>p.id===aPage.id).locked,false);
 assert.equal(after.pages.find(p=>p.id===bPage.id).locked,true);
 await rpc('browser.select',{accountId:account.id,pageId:manual.id});
 assert.equal((await rpc('workspace.status')).page.url,original);
 await until(async()=>await page.locator('.workspace-status').count()===0);
 assert.equal(await page.getByRole('tab').count(),3,'Multiple conversations remain selectable');
 await rpc('browser.select',{accountId:account.id,pageId:bPage.id});
 await page.locator('.preview-canvas img').waitFor();
 await mkdir('test-results',{recursive:true});
 await page.screenshot({path:'test-results/parallel-conversations.png'});
 await execute(aPage.url,'window.fixtureFinish(); window.fixtureHold=false');
 await rpc('queues.resume',{accountId:account.id,conversation:a.conversationId,acknowledged:true});
 await until(async()=> (await rpc('tasks.get',{id:follow.id})).status==='done');
 assert.equal((await rpc('tasks.get',{id:b2.id})).status,'running');
 await execute(bPage.url,'window.fixtureFinish()');
 await until(async()=> (await rpc('tasks.get',{id:b2.id})).status==='done');
 assert.equal(await execute(aPage.url,'window.fixtureSendCount'),2,'A was not replayed');
 assert.equal(await execute(original,'window.fixtureSendCount'),1);
 await rpc('browser.closePage',{accountId:account.id,pageId:bPage.id});
 assert.equal((await rpc('workspace.status')).pages.length,2);
 console.log('Parallel desktop passed: same login, separate pages, original generation preserved, per-conversation FIFO, independent locks/takeover, reply retrieval and notifications.');
} finally {
 if(desktop)await desktop.close();
 assert.ok(directory.startsWith(path.resolve('.')+path.sep+'.test-parallel-'));
 await rm(directory,{recursive:true,force:true});
}
